version: "3.7"

services:
  node:
    image: node:14
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: npm start
    working_dir: /app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://node:3000/"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - .:/app:delegated

  cypress:
    image: cypress/included:7.7.0
    depends_on:
      node:
        condition: service_healthy
    working_dir: /e2e
    entrypoint: cypress
    environment:
      - CYPRESS_VIDEO=false
      - CYPRESS_baseUrl=http://node:3000
      #- DISPLAY=host.docker.internal:0
    volumes:
      - .:/e2e
