---
on:
  push:
    branches:
      - 'develop'
name: Deployment (stg)

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      VERSION: alpha
      APP_VERSION: develop
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (API)
        uses: docker/build-push-action@v2
        with:
          context: ./infrastructure/
          file: ./infrastructure/Dockerfile
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
          push: true
          tags: itkdev/os2display-admin-client:${{ env.VERSION }}

