---
on:
  push:
    branches:
      - 'develop'
name: Build docker image (develop)

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: develop
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: itkdev/os2display-admin-client

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (API)
        uses: docker/build-push-action@v2
        with:
          context: ./infrastructure/
          file: ./infrastructure/Dockerfile
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
